dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: ik3g00+9Vb6SErzkigNZmkP8iDxD/ACxyeKpQ9HNp7Pt646U0twjgogwdzNBsHFV+1SjQ82sSVS6WK9vSM4HZT0eG6ZmRzAzv75c6IAt96SkvffQUmYv6dBZ8EYWIm7htnmOc1mheBOvdSAjzDAcXdKAX3Z+OHfsmKdI/1j2j1ckjAGfP3qz7oKH92LgSh7kQLQ15PiwO/mVfOF2+f61Tkhnp50eaJvWlnvP9myA0QkenuoYW7AnSEfOFAXcTnzVfB79XvVAYesLrVCv/Z2cFP+MHFWqz6uWCcoQv6FlmKdLLC9z0uA44YPLGrFXPpnOR7xBhC8VWYFD/+hkSOeRAm4EQxFGcdqjVmB+o6IEd9i/uTg6WqU3vs6pT6zD5LCfbW/2OR0k5PtxVXNI1wo5GaisegVdiY7Mj4U2H8BjQrSkfSLHDp1ausxybm1bhedYCYmp/Q/mJz1sdaR57g3sUye6HsPhYTUdoL5+qQJKRwr1+vrRVsGxUQFQ7qXo3nn45bN44MTll/sUho8xXJA43aj8YtqRpUUPO1kAIia1iZxByv3jQca4qcjLbDKQtC+POr9pGVkBj3pgupv975hlVfG8hKq8CRixDz8cHdmUR2xT6jpezZXHl9+G1wDWHRDIRH3uJvA5HtYW12Vm5FndStszi5YmoFOctlaubt37TYs=
  file: Gerbers/LOG-102_gerbers.zip
  on:
    repo: w4xzr/LOG-102
  skip_cleanup: 'true'
